### ISSUE TITLE
v23.0.0 Bug - nbcode.sh: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by DadangSudadang** [oracle/javavscode#312] opened 2024-10-29 11:54 UTC
Oracle Java SE Language Server cannot be started due to an error in `oracle.oracle-java-23.0.0/nbcode/bin/nbline.sh`:
```
Initiating server activation
Request to kill LSP server.
Cannot kill: current process is None
Launching Oracle Java SE Language Server with default system JDK and userdir [USER_HOME]/.config/VSCodium/User/workspaceStorage/c4156b640f0d52dc64303d6992d276b4/Oracle.oracle-java
LSP server launching: 38874
LSP server user directory: [USER_HOME]/.config/VSCodium/User/workspaceStorage/c4156b640f0d52dc64303d6992d276b4/Oracle.oracle-java
[USER_HOME]/.vscode-oss/extensions/oracle.oracle-java-23.0.0/nbcode/bin/nbcode.sh: eval: line 138: syntax error near unexpected token `('
[USER_HOME]/.vscode-oss/extensions/oracle.oracle-java-23.0.0/nbcode/bin/nbcode.sh: eval: line 138: `exec /bin/bash "$nbexec" --jdkhome "$jdkhome" --clusters "$clusters" --userdir "${userdir}" --nogui --nosplash --branding nbcode -J-Xmx1G -J-XX:+UseParallelGC -J-XX:GCTimeRatio=4 -J-XX:AdaptiveSizePolicyWeight=90 -J-Djava.awt.headless=true -J--add-opens=java.base/java.net=ALL-UNNAMED -J--add-opens=java.base/java.lang.ref=ALL-UNNAMED -J--add-opens=java.base/java.lang=ALL-UNNAMED -J--add-opens=java.base/java.security=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing.text=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing=ALL-UNNAMED -J--add-opens=java.desktop/java.awt=ALL-UNNAMED -J--add-opens=java.desktop/java.awt.event=ALL-UNNAMED -J--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED -J--add-opens=jdk.jshell/jdk.jshell=ALL-UNNAMED -J--add-modules=jdk.jshell -J--add-exports=java.desktop/sun.awt=ALL-UNNAMED -J--add-exports=java.desktop/java.awt.peer=ALL-UNNAMED -J--add-exports=java.desktop/com.sun.beans.editors=ALL-UNNAMED -J--add-exports=java.desktop/sun.swing=ALL-UNNAMED -J--add-exports=java.desktop/sun.awt.im=ALL-UNNAMED -J--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED -J--add-exports=java.management/sun.management=ALL-UNNAMED -J--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED -J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED -J--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -J--add-exports=jdk.jdeps/com.sun.tools.classfile=ALL-UNNAMED -J--add-exports=jdk.jdeps/com.sun.tools.javap=ALL-UNNAMED -J-XX:+IgnoreUnrecognizedVMOptions  "-J-Dproject.limitScanRoot="/home/esoc-mint:/home/esoc-mint/Documents/work/TA/Exercise5/report-8317652-Exercise 5(9511074)"" "-J-Dnetbeans.extra.dirs=""" "--modules" "--list" "-J-XX:PerfMaxStringConstLength=10240" "--locale" "en"'
Cannot find org.netbeans.modules.java.lsp.server in the log!
Please refer to troubleshooting section for more info: https://github.com/oracle/javavscode/blob/main/README.md#troubleshooting
Request to kill LSP server.
Cannot kill: Requested kill on 38874, current process is None
Oracle Java SE Language Server not enabled
```

Java Extension v23.0.0 running on VSCodium.
```
> java --version
openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7)
OpenJDK 64-Bit Server VM (build 21.0.4+7, mixed mode, sharing)
```
```
> codium --version
1.93.1
dbab3f8e8c5da7ca1bde636806e0a973e497aa01
x64
```
The extension runs fine if I downgrade to v22.1.2.

**Comment by sid-srini** [comment] 2024-10-29 12:15
Thank you @DadangSudadang for reaching out.

This issue is a duplicate of #300 and is occurring due to the code project residing in a path containing spaces. This issue has been fixed in the upcoming release of the extension. I am sorry for the inconvenience this has caused you.

 In the meanwhile, you may use one of the [workarounds suggested there](https://github.com/oracle/javavscode/issues/300#issuecomment-2430988156). Thank you.

**Closed by sid-srini** 2024-10-29 12:15 UTC
Labels: duplicate

**Comment by DadangSudadang** [comment] 2024-10-29 12:22
Thank you for the quick reply. Though the difference ismy project path does not contain any spaces, so I am not sure if it's related or not. I will just downgrade in the meanwhile, thanks.

**Comment by sid-srini** [comment] 2024-10-29 12:29
> Thank you for the quick reply. Though the difference is my project path does not contain any spaces, so I am not sure if it's related or not.

The output you had shared seemed to suggest some path with *Exercise 5*. 
That said, you are right that the problem would arise with even the `(` and `)` in the project path. 

The root cause is related to #300 and both cases will be fixed by the upcoming version due to #301.
So you may try either one of the workarounds to make use of the latest features in the current version of the extension.

Thanks.

**Comment by DadangSudadang** [comment] 2024-10-29 12:34
Ah I did not realize that. Sorry, my bad.

**Comment by sid-srini** [comment] 2024-10-29 12:49
> Ah I did not realize that. Sorry, my bad.
No worries.

Please let us know if you face any other issue. Thanks.
