### ISSUE TITLE
extension is providing incorrect quickfix code actions

### ISSUE THREAD

**Issue by robaho** [oracle/javavscode#153] opened 2024-04-26 13:12 UTC
I see this in the extension host logs:

2024-04-25 20:33:33.896 [warning] Oracle.oracle-java - Code actions of kind 'quickfix 'requested but returned code action is of kind 'refactor.rewrite'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.

This is using the latest v22.0

**Comment by Achal1607** [comment] 2024-04-26 13:20
Can you please provide steps to reproduce the issue where you got incorrect quick actions?

**Comment by robaho** [comment] 2024-04-26 14:26
I am not really sure. I keep getting a popup message like "Element with id 17 is already registered" - which I "think" is a gradle issue - but in looking through the logs to see what might be causing this I found those warnings, so I thought I would report it.

**Comment by Achal1607** [comment] 2024-04-26 14:32
Because the warnings log that you have shared were present in previous version of extensions as well, so problem is faced with quickfix code actions or some gradle issue is there? Can you please clarify this.

**Comment by robaho** [comment] 2024-04-26 15:24
I noticed the message in the logs - which seems to indicate there is a problem with the quickactions code in the extension. I don't have any more details than that - sorry.

**Comment by Achal1607** [comment] 2024-05-10 06:34
FYI: PR raised on the netbeans side: https://github.com/apache/netbeans/pull/7368

**Comment by Achal1607** [comment] 2024-05-14 14:02
Fix available in NB-23

**Comment by robaho** [comment] 2024-05-14 14:41
Nice work!

**Comment by Almushki** [comment] 2024-05-17 15:45
initializing kodezi compiler - Java

compiling code...

ماهو الخطأ في هذا الكود

**Comment by Almushki** [comment] 2024-05-17 15:46
اريد كود حساب اسم معين

**Comment by Achal1607** [comment] 2024-06-17 10:22
Merged

**Closed** 2024-06-17 10:22 UTC
Labels: bug, Apache-Netbeans, patch-ready-YTD
