### ISSUE TITLE
False positive for "Unused import"

### ISSUE THREAD

**Issue by anthonyvdotbe** [oracle/javavscode#66] opened 2023-11-04 09:19 UTC
In the following, the import is said to be unused, even though it isn't:

![image](https://github.com/oracle/javavscode/assets/15714253/fafce854-a72a-4ccd-9fd6-46880a692866)

Removing the import doesn't give an error on the usage of `HttpRouting`, even though doing a `mvn compile` in the terminal fails as expected.

![image](https://github.com/oracle/javavscode/assets/15714253/809de5d1-6f0c-4dd4-8660-f8b9496395e5)

```java
import java.io.IOException;

import io.helidon.config.Config;
import io.helidon.logging.common.LogConfig;
import io.helidon.webserver.WebServer;
import io.helidon.webserver.http.HttpRouting;

public class Main {

    private Main() {
    }

    public static void main(String[] args) throws IOException {
        LogConfig.configureRuntime();

        Config config = Config.create();
        Config.global(config);

        WebServer server = WebServer.builder()
                .config(config.get("server"))
                .routing(Main::routing)
                .build()
                .start();

        System.out.println("WEB server is up! http://localhost:" + server.port() + "/simple-greet");
    }
      


    
    static void routing(HttpRouting.Builder routing) {

        routing.register("/feedback", new FeedbackService());
    }
}
```

**Comment by Achal1607** [comment] 2023-11-17 11:12
Can you also please share pom file of this project to reproduce this issue?

**Comment by anthonyvdotbe** [comment] 2023-11-17 12:00
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.helidon.applications</groupId>
        <artifactId>helidon-se</artifactId>
        <version>4.0.0</version>
        <relativePath/>
    </parent>
    <groupId>...</groupId>
    <artifactId>...</artifactId>
    <version>0.1.0-SNAPSHOT</version>

    <properties>
        <mainClass>...</mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.helidon.webserver</groupId>
            <artifactId>helidon-webserver</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.config</groupId>
            <artifactId>helidon-config-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.webserver.observe</groupId>
            <artifactId>helidon-webserver-observe-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.health</groupId>
            <artifactId>helidon-health-checks</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.logging</groupId>
            <artifactId>helidon-logging-jul</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.json</groupId>
            <artifactId>jakarta.json-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.http.media</groupId>
            <artifactId>helidon-http-media-jsonp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.webserver.observe</groupId>
            <artifactId>helidon-webserver-observe-metrics</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.metrics</groupId>
            <artifactId>helidon-metrics-system-meters</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.webclient</groupId>
            <artifactId>helidon-webclient</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.webserver.testing.junit5</groupId>
            <artifactId>helidon-webserver-testing-junit5</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-libs</id>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by Achal1607** [comment] 2023-11-19 17:24
I used pom file provided by you but was unable to reproduce this issue. Are there any other steps required to reproduce this issue?
Here is the screenshot attached of what I am able to see in VS Code (I am not getting any warnings here)
<img width="934" alt="image" src="https://github.com/oracle/javavscode/assets/55803675/a16a6ff9-2023-42f5-bb72-f745493a6ee1">

**Comment by anthonyvdotbe** [comment] 2023-11-19 18:37
Yes, but I don't know which ones. If I'd have steps to reproduce, I would've given them already.
Please give higher priority to https://github.com/oracle/javavscode/issues/47

**Comment by Achal1607** [comment] 2023-11-20 06:29
Since we were unable to reproduce this issue. I am closing this issue.
Thanks!

**Closed by Achal1607** 2023-11-20 06:29 UTC
Labels: bug, question

**Comment by lahodaj** [comment] 2023-11-20 14:42
FWIW, on the first screenshot, there is obviously some broken coloring - around the WebServer builder. Text coloring is obviously wrong, and the yellow underline span is also highly suspicious (or, rather, also obviously wrong). It could be that there are some stale parse data - I don't know how or why exactly, but the coloring is weird.
