### ISSUE TITLE
Error on formatting pom.xml

### ISSUE THREAD

**Issue by zimmi** [oracle/javavscode#24] opened 2023-10-21 15:12 UTC
### Version
javavscode: 1.0.0
Java: OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

### Steps to reproduce
1.  `Java: New Project...`
2. `Java with Maven`
3.  `Java Application`
4. Pick directory, leave package as default
5. Open in new Window
6. Open `pom.xml`
7. Pressing `CTRL+Shift+I` doesn't start the Language Server automatically, that's probably another issue, so instead:
8. `Java: Clean Workspace` to start the Language Server
9. `CTRL+Shift+I` in the pom.xml

```
[Error - 5:07:27 PM] Request textDocument/formatting failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.lambda$consume$0(Server.java:295)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.netbeans.modules.java.lsp.server.protocol.Server$ConsumeWithLookup$1.consume(Server.java:293)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:109)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 15 more
Caused by: java.lang.ClassCastException: class org.netbeans.modules.java.lsp.server.protocol.FormatterDocument cannot be cast to class org.netbeans.editor.BaseDocument (org.netbeans.modules.java.lsp.server.protocol.FormatterDocument is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @24bb8b10; org.netbeans.editor.BaseDocument is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @900ef56)
	at org.netbeans.modules.xml.text.indent.XMLLexerFormatter.reformat(XMLLexerFormatter.java:73)
	at org.netbeans.modules.xml.text.indent.XMLLexerFormatter.reformat(XMLLexerFormatter.java:795)
	at org.netbeans.modules.xml.text.indent.XMLIndentTask.reindent(XMLIndentTask.java:59)
	at org.netbeans.modules.editor.indent.TaskHandler$MimeItem.runTask(TaskHandler.java:548)
	at org.netbeans.modules.editor.indent.TaskHandler.runTasks(TaskHandler.java:309)
	at org.netbeans.modules.editor.indent.IndentImpl.reformat(IndentImpl.java:349)
	at org.netbeans.modules.editor.indent.api.Reformat.reformat(Reformat.java:129)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.format(TextDocumentServiceImpl.java:1326)
	at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.formatting(TextDocumentServiceImpl.java:1303)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 17 more
```

**Comment by Achal1607** [comment] 2023-10-25 10:09
I tried reproducing it and I can confirm formatting is not working for pom.xml files.

**Comment by Achal1607** [comment] 2023-10-28 05:18
Raised a PR the issue in netbeans:
https://github.com/apache/netbeans/pull/6631

**Comment by zimmi** [comment] 2023-10-28 09:45
> Raised a PR for the issue in netbeans: [apache/netbeans#6631](https://github.com/apache/netbeans/pull/6631)

Awesome, thank you @Achal1607 ! Do you want to fix the issue of javavscode not starting the language server for formatting xml files when it's not already running (point 7) here as well, or do you want me to open another issue?

**Comment by Achal1607** [comment] 2023-11-02 06:15
> > Raised a PR for the issue in netbeans: [apache/netbeans#6631](https://github.com/apache/netbeans/pull/6631)
> 
> Awesome, thank you @Achal1607 ! Do you want to fix the issue of javavscode not starting the language server for formatting xml files when it's not already running (point 7) here as well, or do you want me to open another issue?

Thanks @zimmi for reporting issue.

I think so since it is a java extension, language server should start only when we have at least a file of Java open in the workspace. So, starting the language server for formatting xml files should not be implemented in my opinion.  

I wonder if @lahodaj have some opinions here.

**Comment by zimmi** [comment] 2023-11-02 13:19
IMO: Ideally, javavscode would only support `pom.xml` files directly, not register itself as a general purpose XML editor for other files with the `.xml` extension. Then editing `pom.xml` files should indeed start the language server automatically, because it offers special Maven support (i.e. autocomplete for versions, configuration of maven plugins etc.). I haven't checked if that's possible in VS Code though.

**Comment by Achal1607** [comment] 2024-01-17 11:34
Resolved and merged PR

**Closed by Achal1607** 2024-01-17 11:34 UTC
Labels: bug, Apache-Netbeans, patch-ready-YTD
